export const supplierColumns = [
  {
    name: "supplierId",
    label: "Номер",
    align: "left",
    field: "supplierId",
    sortable: true,
  },
  {
    name: "supplierName",
    label: "Наименование",
    align: "left",
    field: "supplierName",
    sortable: true,
  },
  {
    name: "supplierInn",
    label: "ИНН",
    align: "left",
    field: "supplierInn",
    sortable: true,
  },
  {
    name: "supplierBic",
    label: "БИК",
    align: "left",
    field: "supplierBic",
    sortable: true,
  },
  {
    name: "supplierContactPerson",
    label: "Контакное лицо",
    align: "left",
    field: "supplierContactPerson",
    sortable: true,
  },
  {
    name: "supplierPhone",
    label: "Телефон",
    align: "left",
    field: "supplierPhone",
    sortable: true,
  },
  { name: "actions", label: "Действие", align: "left" },
];
